Repository jestjs/jest, pull requests merged in 2018-02, with the labels that each got.

#5511 Scripts standardize file names: Fix file names in scripts directory
  integration-tests/__tests__/babel_plugin_jest_hoist.test.js
  integration-tests/__tests__/cli-accepts-exact-filenames.test.js
  integration-tests/__tests__/compare_dom_nodes.test.js
  integration-tests/__tests__/console.test.js
  integration-tests/__tests__/console_log_output_when_run_in_band.test.js
  integration-tests/__tests__/coverage_remapping.test.js
  integration-tests/__tests__/coverage_report.test.js
  integration-tests/__tests__/coverage_threshold.test.js
  integration-tests/__tests__/custom_matcher_stack_trace.test.js
  integration-tests/__tests__/custom_reporters.test.js
  integration-tests/__tests__/debug.test.js
  integration-tests/__tests__/execute-tests-once-in-mpr.js
  integration-tests/__tests__/failures.test.js
  integration-tests/__tests__/find_related_files.test.js
  integration-tests/__tests__/force_exit.test.js
  integration-tests/__tests__/globals.test.js
  integration-tests/__tests__/jest.config.js.test.js
  integration-tests/__tests__/jest_changed_files.test.js
  integration-tests/__tests__/jest_require_actual.test.js
  integration-tests/__tests__/jest_require_mock.test.js
  integration-tests/__tests__/log_heap_usage.test.js
  integration-tests/__tests__/module_name_mapper.test.js
  integration-tests/__tests__/multi_project_runner.test.js
  integration-tests/__tests__/native_async_mock.test.js
  integration-tests/__tests__/regex_(char_in_path.test.js
  integration-tests/__tests__/run_tests_by_path.test.js
  integration-tests/__tests__/show_config.test.js
  integration-tests/__tests__/snapshot.test.js
  integration-tests/__tests__/test_failure_exit_code.test.js
  integration-tests/__tests__/test_path_pattern_reporter_message.test.js
  integration-tests/__tests__/timeouts.test.js
  integration-tests/__tests__/transform-linked-modules.test.js
  integration-tests/__tests__/transform.test.js
  integration-tests/__tests__/typescript_coverage.test.js
  integration-tests/__tests__/use_stderr.test.js
  integration-tests/__tests__/version.test.js
  packages/expect/src/__tests__/assertion_counts.test.js
  packages/jest-cli/src/__tests__/search_source.test.js
  packages/jest-haste-map/src/__tests__/index.test.js
  packages/jest-haste-map/src/__tests__/worker.test.js
  packages/jest-haste-map/src/crawlers/__tests__/node.test.js
  packages/jest-haste-map/src/crawlers/__tests__/watchman.test.js
  packages/jest-repl/src/__tests__/jest_repl.test.js
  packages/jest-runtime/src/__tests__/runtime_cli.test.js
  scripts/SkipOnWindows.js
  scripts/_runCommand.js
  scripts/build.js
  scripts/getPackages.js
  scripts/watch.js
Labels: CLA Signed

#5515 capitalize skipOnWindows variable -> SkipOnWindows
  integration-tests/__tests__/babel_plugin_jest_hoist.test.js
  integration-tests/__tests__/cli-accepts-exact-filenames.test.js
  integration-tests/__tests__/compare_dom_nodes.test.js
  integration-tests/__tests__/console.test.js
  integration-tests/__tests__/console_log_output_when_run_in_band.test.js
  integration-tests/__tests__/coverage_remapping.test.js
  integration-tests/__tests__/coverage_report.test.js
  integration-tests/__tests__/coverage_threshold.test.js
  integration-tests/__tests__/custom_matcher_stack_trace.test.js
  integration-tests/__tests__/custom_reporters.test.js
  integration-tests/__tests__/debug.test.js
  integration-tests/__tests__/execute-tests-once-in-mpr.js
  integration-tests/__tests__/failures.test.js
  integration-tests/__tests__/find_related_files.test.js
  integration-tests/__tests__/force_exit.test.js
  integration-tests/__tests__/globals.test.js
  integration-tests/__tests__/jest.config.js.test.js
  integration-tests/__tests__/jest_changed_files.test.js
  integration-tests/__tests__/jest_require_actual.test.js
  integration-tests/__tests__/jest_require_mock.test.js
  integration-tests/__tests__/log_heap_usage.test.js
  integration-tests/__tests__/module_name_mapper.test.js
  integration-tests/__tests__/multi_project_runner.test.js
  integration-tests/__tests__/native_async_mock.test.js
  integration-tests/__tests__/regex_(char_in_path.test.js
  integration-tests/__tests__/run_tests_by_path.test.js
  integration-tests/__tests__/show_config.test.js
  integration-tests/__tests__/snapshot.test.js
  integration-tests/__tests__/test_failure_exit_code.test.js
  integration-tests/__tests__/test_path_pattern_reporter_message.test.js
  integration-tests/__tests__/timeouts.test.js
  integration-tests/__tests__/transform-linked-modules.test.js
  integration-tests/__tests__/transform.test.js
  integration-tests/__tests__/typescript_coverage.test.js
  integration-tests/__tests__/use_stderr.test.js
  integration-tests/__tests__/version.test.js
  packages/expect/src/__tests__/assertion_counts.test.js
  packages/jest-cli/src/__tests__/search_source.test.js
  packages/jest-haste-map/src/__tests__/index.test.js
  packages/jest-haste-map/src/__tests__/worker.test.js
  packages/jest-haste-map/src/crawlers/__tests__/node.test.js
  packages/jest-haste-map/src/crawlers/__tests__/watchman.test.js
  packages/jest-repl/src/__tests__/jest_repl.test.js
  packages/jest-runtime/src/__tests__/runtime_cli.test.js
  scripts/SkipOnWindows.js
Labels: CLA Signed

#5514 add methods to custom and buffered consoles
  CHANGELOG.md
  packages/jest-util/src/Console.js
  packages/jest-util/src/__tests__/buffered_console.test.js
  packages/jest-util/src/__tests__/console.test.js
  packages/jest-util/src/buffered_console.js
  types/Console.js
Labels: CLA Signed

#5291 Documentation for Interactive Snapshot Update
  CHANGELOG.md
  docs/SnapshotTesting.md
  packages/jest-cli/src/__tests__/__snapshots__/snapshot_interactive_mode.test.js.snap
  packages/jest-cli/src/snapshot_interactive_mode.js
  website/static/img/content/interactiveSnapshot.png
  website/static/img/content/interactiveSnapshotUpdate.gif
Labels: CLA Signed

#5523 Add watchAll flag to jest-editor-support
  CHANGELOG.md
  packages/jest-editor-support/index.d.ts
  packages/jest-editor-support/src/Runner.js
  packages/jest-editor-support/src/__tests__/runner.test.js
Labels: CLA Signed

#5524 refactor: strip <rootDir> from collectCoverageFrom values
  CHANGELOG.md
  packages/jest-config/src/__tests__/normalize.test.js
  packages/jest-config/src/normalize.js
Labels: CLA Signed

#5528 Add hyperlink to video URL
  website/pages/en/videos.js
Labels: CLA Signed

#5534 jest-haste-map: fix bug where platform-specific files are removed
  CHANGELOG.md
  packages/jest-haste-map/src/__tests__/index.test.js
  packages/jest-haste-map/src/index.js
  website/pages/en/videos.js
Labels: CLA Signed

#5537 support multiple glob patterns for collectCoverageFrom
  CHANGELOG.md
  docs/CLI.md
  integration-tests/__tests__/__snapshots__/coverage_report.test.js.snap
  integration-tests/__tests__/coverage_report.test.js
  packages/jest-cli/src/cli/args.js
Labels: CLA Signed

#5548 Use preinstalled Yarn on Appveyor
  appveyor.yml
Labels: CLA Signed

#5550 Use `cross-spawn` for running Yarn in integration tests
  integration-tests/__tests__/babel_plugin_jest_hoist.test.js
  integration-tests/__tests__/native_async_mock.test.js
  integration-tests/__tests__/transform.test.js
  integration-tests/__tests__/typescript_coverage.test.js
  integration-tests/utils.js
Labels: CLA Signed

#5553 fix(watchman): Fix watchman checks on Windows
  packages/jest-haste-map/src/crawlers/__tests__/watchman.test.js
  packages/jest-haste-map/src/crawlers/watchman.js
Labels: Bug, Hi-Pri, Windows

#5555 Use native trim instead of regexp
  packages/jest-message-util/src/index.js
Labels: CLA Signed

#5561 Fix jest-circus setup logic
  packages/jest-circus/src/legacy_code_todo_rewrite/jest_adapter.js
Labels: CLA Signed

#5557 Optimize finding top frame in formatPaths
  packages/jest-message-util/src/index.js
Labels: CLA Signed

#5559 Update JestObjectAPI.md
  docs/JestObjectAPI.md
Labels: CLA Signed

#5029 Revert setRawMode on --watch quit (fixes #5028)
  CHANGELOG.md
  packages/jest-cli/src/plugins/quit.js
  packages/jest-cli/src/watch.js
Labels: CLA Signed

#5565 Use v8.serialize when available.
  packages/jest-haste-map/src/__tests__/index.test.js
  packages/jest-haste-map/src/index.js
Labels: CLA Signed

#5569 Optimize getting stack trace in message-util
  packages/jest-message-util/src/index.js
Labels: CLA Signed

#5570 Use native trimLeft, trimRight instead of regexp
  packages/jest-docblock/src/index.js
Labels: CLA Signed

#5560 Replace path sep for testRegex in should_instrument
  CHANGELOG.md
  integration-tests/__tests__/coverage_remapping.test.js
  packages/jest-cli/src/search_source.js
  packages/jest-config/src/normalize.js
Labels: CLA Signed

#5567 Update TutorialReactNative.md
  docs/TutorialReactNative.md
Labels: CLA Signed

#5571 docs: add jest-mongodb example
  CHANGELOG.md
  docs/MongoDB.md
  website/sidebars.json
Labels: CLA Signed

#5547 Issue #5197: Add descriptive error to Expect CalledWith methods when missing optional arguments
  CHANGELOG.md
  packages/expect/src/__tests__/__snapshots__/spy_matchers.test.js.snap
  packages/expect/src/__tests__/spy_matchers.test.js
  packages/expect/src/spy_matchers.js
Labels: CLA Signed

#5536 Print deprecation warnings on CLI flags
  CHANGELOG.md
  integration-tests/__tests__/deprecated_cli_options.test.js
  integration-tests/deprecated-cli-options/__tests__/dummy.js
  integration-tests/deprecated-cli-options/package.json
  integration-tests/snapshot-escape/__tests__/__snapshots__/snapshot_escape_substitution.test.js.snap
  packages/jest-cli/package.json
  packages/jest-cli/src/cli/index.js
  packages/jest-config/src/index.js
  packages/jest-repl/package.json
  packages/jest-repl/src/cli/index.js
  packages/jest-runtime/package.json
  packages/jest-runtime/src/cli/index.js
  packages/jest-util/package.json
  packages/jest-util/src/index.js
  packages/jest-validate/package.json
  packages/jest-validate/src/__tests__/__snapshots__/validate_cli_options.test.js.snap
  packages/jest-validate/src/__tests__/validate_cli_options.test.js
  packages/jest-validate/src/index.js
  packages/jest-validate/src/validate_cli_options.js
Labels: CLA Signed

#5581 Simplify check for -0 in printNumber
  packages/pretty-format/src/index.js
Labels: CLA Signed

#5586 Update discord links, lint markdown
  .github/SUPPORT.md
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  docs/Configuration.md
  docs/Es6ClassMocks.md
  docs/MongoDB.md
  docs/MoreResources.md
  docs/SnapshotTesting.md
  packages/jest-editor-support/README.md
  website/blog/2017-05-06-jest-20-delightful-testing-multi-project-runner.md
  website/core/Footer.js
  website/i18n/en.json
  website/pages/en/help.js
Labels: CLA Signed

#5582 Don't skip configured matchers for exact file names
  CHANGELOG.md
  integration-tests/__tests__/__snapshots__/cli-accepts-exact-filenames.test.js.snap
  integration-tests/__tests__/__snapshots__/cli-handles-exact-filenames.test.js.snap
  integration-tests/__tests__/cli-accepts-exact-filenames.test.js
  integration-tests/__tests__/cli-handles-exact-filenames.test.js
  packages/jest-cli/src/search_source.js
Labels: CLA Signed

#5592 Simplify check -0 in jasmine-utils
  packages/expect/src/jasmine_utils.js
Labels: CLA Signed

#5598 chore: make no-unused-vars eslint rule error
  .eslintrc.js
  packages/jest-cli/src/search_source.js
Labels: CLA Signed

#5505 Make it possible to merge `transform` option with preset
  CHANGELOG.md
  packages/jest-config/src/__tests__/normalize.test.js
  packages/jest-config/src/normalize.js
Labels: CLA Signed

#5600 add a documentation note for project displayName configuration
  CHANGELOG.md
  docs/Configuration.md
Labels: CLA Signed

#5606 docs: link to full list of matchers in opening paragraph
  docs/UsingMatchers.md
Labels: CLA Signed

#5602 chore(deps): upgrade flow to 0.66
  .flowconfig
  package.json
  packages/jest-circus/src/legacy_code_todo_rewrite/jest_adapter_init.js
  packages/jest-jasmine2/src/jasmine/jasmine_light.js
  packages/jest-jasmine2/src/queue_runner.js
  types/Circus.js
  yarn.lock
Labels: CLA Signed

#5596 Optimize print calls in spy matches
  packages/expect/src/spy_matchers.js
Labels: CLA Signed

#5611 fix: make Errors match with ordinary objects (fixes #5359)
  CHANGELOG.md
  packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap
  packages/expect/src/__tests__/matchers.test.js
  packages/expect/src/utils.js
Labels: CLA Signed

#5614 fix: correcting a mislabeled CHANGELOG.md entry
  CHANGELOG.md
Labels: CLA Signed

#5615 fix(watchman): Overhauls how Watchman crawler works fixing Windows
  packages/jest-haste-map/src/crawlers/__tests__/watchman.test.js
  packages/jest-haste-map/src/crawlers/watchman.js
Labels: Bug, CLA Signed, Enhancement, Hi-Pri, Windows

#5576 fix console & buffered console assert behaviour
  CHANGELOG.md
  packages/jest-util/src/Console.js
  packages/jest-util/src/__tests__/buffered_console.test.js
  packages/jest-util/src/__tests__/console.test.js
  packages/jest-util/src/buffered_console.js
Labels: CLA Signed

#5618 Provide `require.main` property
  CHANGELOG.md
  integration-tests/__tests__/require_main.test.js
  integration-tests/require-main/__tests__/loader.test.js
  integration-tests/require-main/example.js
  integration-tests/require-main/loader.js
  integration-tests/require-main/package.json
  packages/jest-runtime/src/__tests__/runtime_require_mock.test.js
  packages/jest-runtime/src/__tests__/runtime_require_module.test.js
  packages/jest-runtime/src/__tests__/test_root/modules_with_main/export_main.js
  packages/jest-runtime/src/__tests__/test_root/modules_with_main/re_export_main.js
  packages/jest-runtime/src/index.js
Labels: CLA Signed

#5622 Update Node version support in README and docs
  CHANGELOG.md
  README.md
  docs/Troubleshooting.md
Labels: CLA Signed

#5624 Update to docs to use yarn
  CHANGELOG.md
  README.md
  docs/CLI.md
  docs/GettingStarted.md
  docs/MigrationGuide.md
  docs/Troubleshooting.md
  docs/TutorialReact.md
  docs/TutorialReactNative.md
  docs/UsingMatchers.md
  docs/Webpack.md
  packages/babel-jest/README.md
  packages/babel-plugin-jest-hoist/README.md
  website/README.md
  website/blog/2016-07-27-jest-14.md
  website/blog/2016-12-15-2016-in-jest.md
  website/blog/2017-02-21-jest-19-immersive-watch-mode-test-platform-improvements.md
Labels: CLA Signed

#5572 Small polish to the plugins API
  packages/jest-cli/src/__tests__/__snapshots__/watch.test.js.snap
  packages/jest-cli/src/__tests__/watch.test.js
  packages/jest-cli/src/base_watch_plugin.js
  packages/jest-cli/src/plugins/quit.js
  packages/jest-cli/src/plugins/test_name_pattern.js
  packages/jest-cli/src/plugins/test_path_pattern.js
  packages/jest-cli/src/plugins/update_snapshots.js
  packages/jest-cli/src/plugins/update_snapshots_interactive.js
  packages/jest-cli/src/types.js
  packages/jest-cli/src/watch.js
Labels: CLA Signed

#5627 Remove debug snapshot
  packages/jest-cli/src/__tests__/__snapshots__/watch.test.js.snap
  packages/jest-cli/src/__tests__/watch.test.js
  packages/jest-cli/src/plugins/update_snapshots_interactive.js
Labels: CLA Signed

#5626 Examples/standardize folder names
  docs/ManualMocks.md
  examples/getting-started/.babelrc
  examples/getting-started/package.json
  examples/getting-started/sum.js
  examples/getting-started/sum.test.js
  examples/manual-mocks/.babelrc
  examples/manual-mocks/FileSummarizer.js
  examples/manual-mocks/__mocks__/fs.js
  examples/manual-mocks/__mocks__/lodash.js
  examples/manual-mocks/__tests__/file_summarizer.test.js
  examples/manual-mocks/__tests__/lodashMocking.test.js
  examples/manual-mocks/__tests__/user.test.js
  examples/manual-mocks/__tests__/userMocked.test.js
  examples/manual-mocks/models/__mocks__/user.js
  examples/manual-mocks/models/user.js
  examples/manual-mocks/package.json
  examples/module-mock/.babelrc
  examples/module-mock/__tests__/full_mock.js
  examples/module-mock/__tests__/mock_per_test.js
  examples/module-mock/__tests__/partial_mock.js
  examples/module-mock/fruit.js
  examples/module-mock/package.json
Labels: CLA Signed

#5541 add versioned documentation to the website
  .eslintrc.js
  CHANGELOG.md
  website/package.json
  website/pages/en/versions.js
  website/versioned_docs/version-22.3/CLI.md
  website/versioned_docs/version-22.3/Configuration.md
  website/versioned_docs/version-22.3/Es6ClassMocks.md
  website/versioned_docs/version-22.3/ExpectAPI.md
  website/versioned_docs/version-22.3/GettingStarted.md
  website/versioned_docs/version-22.3/GlobalAPI.md
  website/versioned_docs/version-22.3/JestObjectAPI.md
  website/versioned_docs/version-22.3/JestPlatform.md
  website/versioned_docs/version-22.3/ManualMocks.md
  website/versioned_docs/version-22.3/MigrationGuide.md
  website/versioned_docs/version-22.3/MockFunctionAPI.md
  website/versioned_docs/version-22.3/MockFunctions.md
  website/versioned_docs/version-22.3/MongoDB.md
  website/versioned_docs/version-22.3/MoreResources.md
  website/versioned_docs/version-22.3/Puppeteer.md
  website/versioned_docs/version-22.3/SetupAndTeardown.md
  website/versioned_docs/version-22.3/SnapshotTesting.md
  website/versioned_docs/version-22.3/TestingAsyncCode.md
  website/versioned_docs/version-22.3/TestingFrameworks.md
  website/versioned_docs/version-22.3/TimerMocks.md
  website/versioned_docs/version-22.3/Troubleshooting.md
  website/versioned_docs/version-22.3/TutorialAsync.md
  website/versioned_docs/version-22.3/TutorialReact.md
  website/versioned_docs/version-22.3/TutorialReactNative.md
  website/versioned_docs/version-22.3/TutorialjQuery.md
  website/versioned_docs/version-22.3/UsingMatchers.md
  website/versioned_docs/version-22.3/Webpack.md
  website/versioned_sidebars/version-22.3-sidebars.json
  website/versions.json
Labels: CLA Signed

#5594 [WIP] Remove usage of `retainLines`
  .babelrc
  CHANGELOG.md
  integration-tests/__tests__/__snapshots__/failures.test.js.snap
  integration-tests/__tests__/location_in_results.test.js
  integration-tests/location-in-results/__tests__/test.js
  packages/babel-jest/src/index.js
  packages/jest-jasmine2/package.json
  packages/jest-jasmine2/src/index.js
  packages/jest-runner/src/run_test.js
  packages/jest-runtime/src/index.js
  packages/jest-util/package.json
  packages/jest-util/src/__tests__/buffered_console.test.js
  packages/jest-util/src/__tests__/get_callsite.test.js
  packages/jest-util/src/buffered_console.js
  packages/jest-util/src/get_callsite.js
  packages/jest-util/src/index.js
  types/SourceMaps.js
Labels: CLA Signed

#5625 [jest-editor-support] update TypeScript definition
  CHANGELOG.md
  packages/jest-editor-support/index.d.ts
Labels: CLA Signed

#5638 Add how to mock scoped modules to Manual Mocks doc
  CHANGELOG.md
  docs/ManualMocks.md
Labels: CLA Signed

#5637 update istanbul-api
  integration-tests/__tests__/__snapshots__/coverage_report.test.js.snap
  integration-tests/__tests__/__snapshots__/coverage_threshold.test.js.snap
  integration-tests/__tests__/__snapshots__/transform.test.js.snap
  integration-tests/__tests__/__snapshots__/typescript_coverage.test.js.snap
  yarn.lock
Labels: CLA Signed

#5639 Jest got too popular
  website/pages/en/users.js
Labels: CLA Signed

#5640 fix(watchman): Parallelize Watchman calls in crawler again
  packages/jest-haste-map/src/crawlers/watchman.js
Labels: Bug, CLA Signed, Enhancement, Hi-Pri

#5642 Force haste map regeneration on deserialization error
  packages/jest-haste-map/src/index.js
Labels: CLA Signed

#4858 Use outputStream instead of stdout for output file
  packages/jest-cli/src/run_jest.js
Labels: CLA Signed, On Hold

#5512 Improve description line when assertion fails: part 2
  CHANGELOG.md
  integration-tests/__tests__/__snapshots__/failures.test.js.snap
  integration-tests/__tests__/jasmine_async.test.js
  packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap
  packages/expect/src/matchers.js
  packages/jest-jasmine2/src/__tests__/__snapshots__/matchers.test.js.snap
  packages/jest-matcher-utils/src/index.js
Labels: CLA Signed

#5645 Lint markdown in CI
  docs/ManualMocks.md
  package.json
Labels: CLA Signed

#5646 tests(colors): Force-disable colors on tests for consistent snapshots
  integration-tests/runJest.js
Labels: CLA Signed

#5651 use prettylint for markdown
  package.json
  yarn.lock
Labels: CLA Signed

#5652 tests(chalk): Force chalk to on in matcher tests for consistency
  packages/expect/src/__tests__/matchers.test.js
Labels: Bug :bug:, CLA Signed, Infrastructure

#5656 Fix Good First Issue link in README.md
  README.md
Labels: cla signed

#5658 Update `jest-editor-support` `Settings` to use spawn in shell option
  CHANGELOG.md
  packages/jest-editor-support/index.d.ts
  packages/jest-editor-support/src/Settings.js
  packages/jest-editor-support/src/__tests__/settings.test.js
Labels: cla signed

#5672 Fix: unbreak master
  .circleci/config.yml
  CHANGELOG.md
  packages/jest-editor-support/src/__tests__/settings.test.js
Labels: cla signed

#5674 Improve the error message when 2 projects resolve to the same config
  CHANGELOG.md
  integration-tests/__tests__/multi_project_runner.test.js
  packages/jest-cli/src/cli/index.js
Labels: cla signed

#5680 exclude __mocks__ from the build step
  scripts/build.js
Labels: cla signed

#5636 jest-circus test utilities
  package.json
  packages/jest-circus/src/__mocks__/test_event_handler.js
  packages/jest-circus/src/__mocks__/test_utils.js
  packages/jest-circus/src/__tests__/__snapshots__/hooks.test.js.snap
  packages/jest-circus/src/__tests__/hooks.test.js
Labels: CLA Signed :heavy_check_mark:

#5679 don't use `master` as hg bookmark name
  integration-tests/__tests__/jest_changed_files.test.js
Labels: cla signed

#5681 Update dependencies
  .flowconfig
  CONTRIBUTING.md
  docs/MongoDB.md
  docs/Puppeteer.md
  docs/TutorialReact.md
  lerna.json
  package.json
  packages/expect/src/__tests__/spy_matchers.test.js
  packages/expect/src/spy_matchers.js
  packages/jest-cli/package.json
  packages/jest-repl/package.json
  packages/jest-runtime/package.json
  packages/jest-runtime/src/__tests__/__snapshots__/script_transformer.test.js.snap
  website/blog/2016-10-03-jest-16.md
  website/blog/2017-12-18-jest-22.md
  website/versioned_docs/version-22.3/MongoDB.md
  website/versioned_docs/version-22.3/Puppeteer.md
  website/versioned_docs/version-22.3/TutorialReact.md
  yarn.lock
Labels: cla signed

#5683 add empty .watchmanconfig
  .watchmanconfig
Labels: cla signed

#5678 don't use watchman in MPR test
  integration-tests/__tests__/multi_project_runner.test.js
Labels: cla signed

#5675 Add jest community section to docs
  docs/JestCommunity.md
  website/i18n/en.json
  website/sidebars.json
Labels: cla signed

#5686 Remove needless replace by regexp
  packages/jest-editor-support/src/Runner.js
Labels: cla signed

#5684 Update MockFunctionAPI doc to be consistent like other API docs
  docs/MockFunctionAPI.md
Labels: cla signed

#5688 Fix restore-cache issue on CircleCi
  .circleci/config.yml
Labels: cla signed

#5691 Add parseInt, parseFloat and isNaN to mock whitelist
  packages/babel-plugin-jest-hoist/src/index.js
Labels: cla signed

#5692 remove retainLines from coverage instrumentation
  CHANGELOG.md
  docs/TutorialReact.md
  packages/jest-runtime/src/__tests__/__snapshots__/script_transformer.test.js.snap
  packages/jest-runtime/src/script_transformer.js
Labels: cla signed

#5532 fixes #5531
  packages/jest-jasmine2/src/__tests__/Suite.test.js
  packages/jest-jasmine2/src/jasmine/Suite.js
Labels: CLA Signed :heavy_check_mark:
