Repository jestjs/jest, pull requests merged in 2020-12, with the labels that each got.

#10892 fix: unable to cyclic ES modules
  CHANGELOG.md
  e2e/__tests__/__snapshots__/nativeEsm.test.ts.snap
  e2e/native-esm/__tests__/native-esm.test.js
  e2e/native-esm/circularDependentA.mjs
  e2e/native-esm/circularDependentB.mjs
  packages/jest-runtime/src/index.ts
Labels: cla signed

#10900 chore: convert jest-runner to ESM
  CHANGELOG.md
  e2e/transform/transform-runner/runner.ts
  packages/jest-core/src/TestScheduler.ts
  packages/jest-core/src/__tests__/SearchSource.test.ts
  packages/jest-runner/src/index.ts
Labels: cla signed

#10889 docs: Update incorrect implementation of custom inline snapshot matcher
  docs/ExpectAPI.md
  website/versioned_docs/version-25.x/ExpectAPI.md
Labels: cla signed

#10873 chore: use own eslint rules, not from fb config
  .eslintrc.js
  e2e/__tests__/__snapshots__/coverageTransformInstrumented.test.ts.snap
  e2e/__tests__/__snapshots__/coverageWithoutTransform.test.ts.snap
  e2e/coverage-transform-instrumented/covered.js
  e2e/coverage-without-transform/some-random-file.js
  e2e/native-esm/__tests__/native-esm.test.js
  e2e/reset-modules/__tests__/resetModules.test.js
  e2e/snapshot-serializers/plugins/bar.js
  fixtures/parser_tests.js
  package.json
  packages/jest-circus/src/index.ts
  packages/jest-config/src/normalize.ts
  packages/jest-core/src/runJest.ts
  packages/jest-jasmine2/src/jasmine/Env.ts
  yarn.lock
Labels: cla signed

#10906 chore: migrate jest-jasmine to ESM
  CHANGELOG.md
  packages/jest-jasmine2/src/index.ts
Labels: cla signed

#10893 chore: update type definitions for coverageThreshold
  packages/jest-types/src/Config.ts
  test-types/top-level-config.test.ts
Labels: cla signed

#10903 fix(babel-plugin-jest-hoist): allow using module wrapper arguments in hoisted mock factory function
  CHANGELOG.md
  packages/babel-plugin-jest-hoist/src/index.ts
Labels: cla signed

#10910 chore: fix react-native example
  examples/react-native/jest.config.js
Labels: cla signed

#10913 chore: patch fsevents ts file
  package.json
  patches/fsevents.patch
  yarn.lock
Labels: cla signed

#10836 Add generator function to accepted hook types
  packages/jest-circus/src/utils.ts
  packages/jest-types/src/Global.ts
  test-types/top-level-globals.test.ts
Labels: cla signed

#10823 feat: support files other than js to be ESM
  CHANGELOG.md
  docs/Configuration.md
  docs/ECMAScriptModules.md
  e2e/__tests__/__snapshots__/showConfig.test.ts.snap
  e2e/__tests__/nativeEsmTypescript.test.ts
  e2e/native-esm-typescript/__tests__/double.test.ts
  e2e/native-esm-typescript/babel.config.js
  e2e/native-esm-typescript/double.ts
  e2e/native-esm-typescript/package.json
  packages/jest-circus/src/legacy-code-todo-rewrite/jestAdapter.ts
  packages/jest-config/package.json
  packages/jest-config/src/Defaults.ts
  packages/jest-config/src/ValidConfig.ts
  packages/jest-config/src/__tests__/__snapshots__/normalize.test.js.snap
  packages/jest-config/src/__tests__/normalize.test.js
  packages/jest-config/src/index.ts
  packages/jest-config/src/normalize.ts
  packages/jest-core/src/lib/__tests__/__snapshots__/logDebugMessages.test.ts.snap
  packages/jest-jasmine2/src/index.ts
  packages/jest-repl/src/cli/runtime-cli.ts
  packages/jest-resolve/src/shouldLoadAsEsm.ts
  packages/jest-runner/src/runTest.ts
  packages/jest-runtime/src/index.ts
  packages/jest-transform/src/__tests__/__snapshots__/script_transformer.test.ts.snap
  packages/jest-types/src/Config.ts
  packages/test-utils/src/config.ts
  yarn.lock
Labels: cla signed

#10890 docs: changed UsingMatchers array example
  docs/UsingMatchers.md
  website/versioned_docs/version-22.x/UsingMatchers.md
Labels: cla signed

#10901 feat(jest-runtime): share cacheFS between runtime and transformer
  CHANGELOG.md
  docs/CodeTransformation.md
  packages/jest-repl/src/cli/repl.ts
  packages/jest-runtime/src/index.ts
  packages/jest-transform/src/ScriptTransformer.ts
  packages/jest-transform/src/__tests__/__snapshots__/script_transformer.test.ts.snap
  packages/jest-transform/src/__tests__/script_transformer.test.ts
  packages/jest-transform/src/types.ts
Labels: cla signed

#10919 fix: vendor node crawler from sane
  .eslintrc.js
  CHANGELOG.md
  jest.config.js
  package.json
  packages/jest-haste-map/package.json
  packages/jest-haste-map/src/__tests__/index.test.js
  packages/jest-haste-map/src/index.ts
  packages/jest-haste-map/src/watchers/FSEventsWatcher.ts
  packages/jest-haste-map/src/watchers/NodeWatcher.js
  packages/jest-haste-map/src/watchers/RecrawlWarning.js
  packages/jest-haste-map/src/watchers/WatchmanWatcher.js
  packages/jest-haste-map/src/watchers/common.js
  patches/fsevents.patch
  scripts/checkCopyrightHeaders.js
  yarn.lock
Labels: cla signed

#10512 feat(globals): make test return values stricter
  CHANGELOG.md
  packages/jest-circus/src/legacy-code-todo-rewrite/jestAdapterInit.ts
  packages/jest-circus/src/utils.ts
  packages/jest-jasmine2/src/jasmineAsyncInstall.ts
  packages/jest-types/src/Circus.ts
  packages/jest-types/src/Global.ts
  test-types/top-level-globals.test.ts
Labels: TypeScript, cla signed

#9969 chore: remove getSourceMapInfo from jest-runtime
  CHANGELOG.md
  packages/jest-runtime/src/index.ts
Labels: cla signed

#10650 Remove recursiveBlacklist option from jest-validate
  CHANGELOG.md
  packages/jest-config/src/normalize.ts
  packages/jest-validate/src/__tests__/validate.test.ts
  packages/jest-validate/src/types.ts
  packages/jest-validate/src/validate.ts
Labels: cla signed, 💣 Breaking change

#10119 Make toContain more strict with the received type
  CHANGELOG.md
  packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap
  packages/expect/src/__tests__/matchers.test.js
  packages/expect/src/matchers.ts
Labels: cla signed

#10324 chore: make TestWatcher extend emittery
  CHANGELOG.md
  packages/jest-core/package.json
  packages/jest-core/src/TestScheduler.ts
  packages/jest-core/src/TestWatcher.ts
  packages/jest-runner/src/index.ts
  packages/jest-runner/src/types.ts
  yarn.lock
Labels: cla signed

#10348 chore(jest-haste-map): remove support for ignorePattern as function
  CHANGELOG.md
  packages/jest-haste-map/src/__tests__/index.test.js
  packages/jest-haste-map/src/index.ts
Labels: cla signed

#10874 feat: use modern fake timers by default
  CHANGELOG.md
  docs/JestObjectAPI.md
  e2e/fake-promises/immediate/__tests__/generator.test.js
  packages/jest-circus/src/legacy-code-todo-rewrite/jestAdapter.ts
  packages/jest-jasmine2/src/index.ts
  packages/jest-runtime/src/index.ts
Labels: cla signed, 💣 Breaking change

#10623 Fix: jest-worker: should not expose `.default` babel interop
  CHANGELOG.md
  packages/jest-haste-map/src/__tests__/index.test.js
  packages/jest-haste-map/src/index.ts
  packages/jest-reporters/src/CoverageReporter.ts
  packages/jest-runner/src/__tests__/testRunner.test.ts
  packages/jest-runner/src/index.ts
  packages/jest-worker/README.md
  packages/jest-worker/src/__performance_tests__/test.js
  packages/jest-worker/src/__tests__/index.test.js
  packages/jest-worker/src/__tests__/process-integration.test.js
  packages/jest-worker/src/__tests__/thread-integration.test.js
  packages/jest-worker/src/index.ts
Labels: cla signed, 💣 Breaking change

#10920 chore: ./jest requires bash
  jest
Labels: cla signed

#10924 chore: fix failing tests
  package.json
  yarn.lock
Labels: cla signed

#10918 refactor(jest-runtime,jest-transform): add readonly for some class fields
  packages/jest-runtime/src/index.ts
  packages/jest-transform/src/ScriptTransformer.ts
Labels: cla signed

#9968 chore: remove mapCoverage remainings; remove deprecated CLI options test
  CHANGELOG.md
  e2e/__tests__/deprecatedCliOptions.test.ts
  e2e/deprecated-cli-options/__tests__/dummy.js
  e2e/deprecated-cli-options/package.json
  packages/jest-cli/src/cli/args.ts
  packages/jest-config/src/Deprecated.ts
  packages/jest-config/src/normalize.ts
  packages/jest-types/src/Config.ts
  packages/jest-types/src/Transform.ts
Labels: cla signed

#10355 chore(test-result): remove deprecated `sourcemap` property
  packages/jest-circus/src/legacy-code-todo-rewrite/jestAdapterInit.ts
  packages/jest-core/src/ReporterDispatcher.ts
  packages/jest-test-result/src/helpers.ts
  packages/jest-test-result/src/types.ts
Labels: cla signed

#10925 fix: move binary file declaration from runtime to repl
  CHANGELOG.md
  packages/jest-repl/package.json
  packages/jest-runtime/package.json
  scripts/buildUtils.js
  yarn.lock
Labels: cla signed

#10926 feat(transform): pass config options through to transformer
  CHANGELOG.md
  docs/CodeTransformation.md
  e2e/__tests__/__snapshots__/transform.test.ts.snap
  packages/babel-jest/src/index.ts
  packages/jest-repl/src/cli/repl.ts
  packages/jest-transform/src/ScriptTransformer.ts
  packages/jest-transform/src/__tests__/ScriptTransformer.test.ts
  packages/jest-transform/src/__tests__/__snapshots__/ScriptTransformer.test.ts.snap
  packages/jest-transform/src/__tests__/shouldInstrument.test.ts
  packages/jest-transform/src/types.ts
Labels: cla signed

#10922 Document and test custom, async, inline snapshot matcher
  docs/ExpectAPI.md
  e2e/__tests__/__snapshots__/customInlineSnapshotMatchers.test.ts.snap
  e2e/__tests__/customInlineSnapshotMatchers.test.ts
  e2e/custom-inline-snapshot-matchers/__tests__/asynchronous.test.js
  e2e/custom-inline-snapshot-matchers/package.json
  website/versioned_docs/version-25.x/ExpectAPI.md
Labels: cla signed

#10929 Ensure `toContain` only accepts strings when `received` is a string
  CHANGELOG.md
  packages/expect/src/__tests__/__snapshots__/matchers.test.js.snap
  packages/expect/src/__tests__/matchers.test.js
  packages/expect/src/matchers.ts
Labels: cla signed

#10930 docs: Rectify typo in tutorialReactNative
  docs/TutorialReactNative.md
  website/versioned_docs/version-22.x/TutorialReactNative.md
  website/versioned_docs/version-25.x/TutorialReactNative.md
Labels: cla signed

#10941 chore: verify TS project references are correct
  package.json
  packages/jest-circus/tsconfig.json
  packages/jest-cli/tsconfig.json
  packages/jest-config/tsconfig.json
  packages/jest-core/tsconfig.json
  packages/jest-environment/tsconfig.json
  packages/jest-fake-timers/tsconfig.json
  packages/jest-haste-map/tsconfig.json
  packages/jest-leak-detector/tsconfig.json
  packages/jest-reporters/tsconfig.json
  packages/jest-resolve-dependencies/tsconfig.json
  packages/jest-resolve/tsconfig.json
  packages/jest-runner/tsconfig.json
  packages/jest-runtime/tsconfig.json
  packages/jest-test-sequencer/tsconfig.json
  packages/pretty-format/tsconfig.json
  scripts/buildTs.js
  yarn.lock
Labels: cla signed

#8766 [jest-each] Template table heading validation and extraction
  CHANGELOG.md
  packages/jest-each/src/__tests__/__snapshots__/template.test.ts.snap
  packages/jest-each/src/__tests__/template.test.ts
  packages/jest-each/src/bind.ts
  packages/jest-each/src/validation.ts
Labels: cla signed, 💣 Breaking change

#10947 feat(jest-circus,jest-jasmine2): throw when describe returns a value
  CHANGELOG.md
  e2e/__tests__/__snapshots__/declarationErrors.test.ts.snap
  e2e/__tests__/declarationErrors.test.ts
  e2e/declaration-errors/__tests__/describeReturnPromise.test.js
  e2e/declaration-errors/__tests__/describeReturnSomething.test.js
  packages/jest-circus/src/index.ts
  packages/jest-jasmine2/src/jasmine/Env.ts
Labels: cla signed

#10942 docs: cleanup `mock.calls` structure
  docs/MockFunctions.md
  website/versioned_docs/version-22.x/MockFunctions.md
  website/versioned_docs/version-23.x/MockFunctions.md
Labels: cla signed

#10963 fix(jest-runtime): prevent global module registry from leaking into isolateModules registry
  CHANGELOG.md
  packages/jest-runtime/src/__tests__/runtime_require_module_or_mock.test.js
  packages/jest-runtime/src/index.ts
Labels: cla signed

#10961 ci: only fetch dependencies once
  .github/workflows/nodejs.yml
Labels: cla signed

#10624 feat: fail tests when multiple `done()` calls are made
  CHANGELOG.md
  e2e/__tests__/__snapshots__/callDoneTwice.test.ts.snap
  e2e/__tests__/__snapshots__/circusDeclarationErrors.test.ts.snap
  e2e/__tests__/callDoneTwice.test.ts
  e2e/__tests__/doneInHooks.test.ts
  e2e/call-done-twice/__tests__/index.test.js
  e2e/call-done-twice/package.json
  e2e/done-in-hooks/__tests__/index.test.js
  e2e/done-in-hooks/package.json
  packages/jest-circus/src/eventHandler.ts
  packages/jest-circus/src/utils.ts
  packages/jest-core/src/__tests__/SearchSource.test.ts
  packages/jest-types/src/Circus.ts
Labels: cla signed, 💣 Breaking change

#10572 fix(jest-config): move json behind ts
  CHANGELOG.md
  docs/Configuration.md
  e2e/__tests__/__snapshots__/showConfig.test.ts.snap
  packages/jest-cli/src/init/__tests__/__snapshots__/init.test.js.snap
  packages/jest-config/src/Defaults.ts
  packages/jest-config/src/__tests__/normalize.test.js
Labels: cla signed, 💣 Breaking change

#10968 chore: use `Map`s throughout jest-runtime
  CHANGELOG.md
  packages/jest-repl/src/cli/runtime-cli.ts
  packages/jest-resolve/src/index.ts
  packages/jest-runner/src/runTest.ts
  packages/jest-runtime/src/__mocks__/createRuntime.js
  packages/jest-runtime/src/__tests__/__snapshots__/runtime_require_module_no_ext.test.js.snap
  packages/jest-runtime/src/index.ts
  packages/jest-source-map/src/__tests__/getCallsite.test.ts
  packages/jest-source-map/src/getCallsite.ts
  packages/jest-source-map/src/types.ts
Labels: cla signed

#10966 feat(jest-haste-map): handle injected scm clocks
  CHANGELOG.md
  packages/jest-haste-map/src/crawlers/__tests__/watchman.test.js
  packages/jest-haste-map/src/crawlers/watchman.ts
  packages/jest-haste-map/src/types.ts
Labels: cla signed

#10970 chore: use async-await in tests
  packages/jest-haste-map/src/__tests__/index.test.js
  packages/jest-haste-map/src/crawlers/__tests__/node.test.js
  packages/jest-haste-map/src/crawlers/__tests__/watchman.test.js
  packages/jest-haste-map/src/watchers/FSEventsWatcher.ts
  packages/jest-runtime/src/__tests__/Runtime-sourceMaps.test.js
  packages/jest-runtime/src/__tests__/runtime_create_mock_from_module.test.js
  packages/jest-runtime/src/__tests__/runtime_environment.test.js
  packages/jest-runtime/src/__tests__/runtime_internal_module.test.js
  packages/jest-runtime/src/__tests__/runtime_jest_fn.js
  packages/jest-runtime/src/__tests__/runtime_jest_spy_on.test.js
  packages/jest-runtime/src/__tests__/runtime_mock.test.js
  packages/jest-runtime/src/__tests__/runtime_module_directories.test.js
  packages/jest-runtime/src/__tests__/runtime_node_path.test.js
  packages/jest-runtime/src/__tests__/runtime_require_actual.test.js
  packages/jest-runtime/src/__tests__/runtime_require_cache.test.js
  packages/jest-runtime/src/__tests__/runtime_require_mock.test.js
  packages/jest-runtime/src/__tests__/runtime_require_module.test.js
  packages/jest-runtime/src/__tests__/runtime_require_module_or_mock.test.js
  packages/jest-runtime/src/__tests__/runtime_require_module_or_mock_transitive_deps.test.js
Labels: cla signed

#10974 Link directly to #testing on Reactiflux
  .github/ISSUE_TEMPLATE/question.md
  .github/SUPPORT.md
  CONTRIBUTING.md
  docs/MoreResources.md
  website/blog/2016-03-11-javascript-unit-testing-performance.md
  website/blog/2016-12-15-2016-in-jest.md
  website/blog/2017-05-06-jest-20-delightful-testing-multi-project-runner.md
  website/blog/2018-05-29-jest-23-blazing-fast-delightful-testing.md
  website/core/Footer.js
  website/pages/en/help.js
  website/versioned_docs/version-22.x/MoreResources.md
Labels: cla signed

#10975 chore(runtime): make arguments mandatory
  packages/jest-circus/src/legacy-code-todo-rewrite/jestAdapter.ts
  packages/jest-circus/src/legacy-code-todo-rewrite/jestAdapterInit.ts
  packages/jest-repl/src/cli/runtime-cli.ts
  packages/jest-runtime/src/__mocks__/createRuntime.js
  packages/jest-runtime/src/index.ts
  packages/jest-test-result/src/types.ts
Labels: cla signed

#10978 chore: improve git version detection in tests
  e2e/__tests__/jestChangedFiles.test.ts
  e2e/__tests__/onlyChanged.test.ts
Labels: cla signed

#10958 Make testFailureExitCode compatible with bail option
  CHANGELOG.md
  e2e/__tests__/testFailureExitCode.test.ts
  packages/jest-core/src/TestScheduler.ts
  packages/pretty-format/src/__tests__/ReactElement.test.ts
  packages/pretty-format/src/__tests__/react.test.tsx
Labels: cla signed

#10977 chore: make node-notifier a peer dep
  CHANGELOG.md
  package.json
  packages/jest-cli/package.json
  packages/jest-core/package.json
  packages/jest-reporters/package.json
  packages/jest-reporters/src/NotifyReporter.ts
  packages/jest-reporters/src/__tests__/NotifyReporter.test.ts
  packages/jest/package.json
  yarn.lock
Labels: cla signed

#10980 feat: sequencer saving may be async
  CHANGELOG.md
  e2e/__tests__/customTestSequencers.test.ts
  e2e/custom-test-sequencer/testSequencerAsync.js
  packages/jest-core/src/runJest.ts
Labels: cla signed

#10921 PriorityQueue implementation for jest-worker
  CHANGELOG.md
  packages/jest-worker/README.md
  packages/jest-worker/src/Farm.ts
  packages/jest-worker/src/FifoQueue.ts
  packages/jest-worker/src/PriorityQueue.ts
  packages/jest-worker/src/__performance_tests__/test.js
  packages/jest-worker/src/__tests__/Farm.test.js
  packages/jest-worker/src/__tests__/FifoQueue.test.js
  packages/jest-worker/src/__tests__/PriorityQueue.test.js
  packages/jest-worker/src/index.ts
  packages/jest-worker/src/types.ts
Labels: cla signed

#10984 fix(worker): do not swallow errors when sending custom messages
  CHANGELOG.md
  packages/jest-worker/src/workers/messageParent.ts
Labels: cla signed

#10982 chore(e2e tests): right trim stdout and stderr consistently
  e2e/Utils.ts
  e2e/__tests__/__snapshots__/asyncAndCallback.test.ts.snap
  e2e/__tests__/__snapshots__/callDoneTwice.test.ts.snap
  e2e/__tests__/__snapshots__/chaiAssertionLibrary.ts.snap
  e2e/__tests__/__snapshots__/circusDeclarationErrors.test.ts.snap
  e2e/__tests__/__snapshots__/console.test.ts.snap
  e2e/__tests__/__snapshots__/consoleAfterTeardown.test.ts.snap
  e2e/__tests__/__snapshots__/coverageHandlebars.test.ts.snap
  e2e/__tests__/__snapshots__/coverageReport.test.ts.snap
  e2e/__tests__/__snapshots__/coverageThreshold.test.ts.snap
  e2e/__tests__/__snapshots__/coverageWithoutTransform.test.ts.snap
  e2e/__tests__/__snapshots__/customInlineSnapshotMatchers.test.ts.snap
  e2e/__tests__/__snapshots__/customMatcherStackTrace.test.ts.snap
  e2e/__tests__/__snapshots__/declarationErrors.test.ts.snap
  e2e/__tests__/__snapshots__/detectOpenHandles.ts.snap
  e2e/__tests__/__snapshots__/domDiffing.test.ts.snap
  e2e/__tests__/__snapshots__/each.test.ts.snap
  e2e/__tests__/__snapshots__/emptyDescribeWithHooks.test.ts.snap
  e2e/__tests__/__snapshots__/environmentAfterTeardown.test.ts.snap
  e2e/__tests__/__snapshots__/errorOnDeprecated.test.ts.snap
  e2e/__tests__/__snapshots__/expectAsyncMatcher.test.ts.snap
  e2e/__tests__/__snapshots__/failures.test.ts.snap
  e2e/__tests__/__snapshots__/findRelatedFiles.test.ts.snap
  e2e/__tests__/__snapshots__/moduleNameMapper.test.ts.snap
  e2e/__tests__/__snapshots__/nestedTestDefinitions.test.ts.snap
  e2e/__tests__/__snapshots__/processExit.test.ts.snap
  e2e/__tests__/__snapshots__/requireAfterTeardown.test.ts.snap
  e2e/__tests__/__snapshots__/resolveNoFileExtensions.test.ts.snap
  e2e/__tests__/__snapshots__/stackTraceSourceMapsWithCoverage.test.ts.snap
  e2e/__tests__/__snapshots__/testTodo.test.ts.snap
  e2e/__tests__/__snapshots__/transform.test.ts.snap
  e2e/__tests__/__snapshots__/typescriptCoverage.test.ts.snap
  e2e/__tests__/__snapshots__/v8Coverage.test.ts.snap
  e2e/__tests__/__snapshots__/watchModeOnlyFailed.test.ts.snap
  e2e/__tests__/__snapshots__/watchModePatterns.test.ts.snap
  e2e/__tests__/__snapshots__/watchModeUpdateSnapshot.test.ts.snap
  e2e/__tests__/__snapshots__/wrongEnv.test.ts.snap
  e2e/runJest.ts
  packages/jest-worker/src/__performance_tests__/test.js
Labels: cla signed

#10989 fix(expect): resolve `message` on assertion errors
  CHANGELOG.md
  e2e/__tests__/failureDetailsProperty.test.ts
  packages/expect/src/index.ts
Labels: cla signed

#10981 fix(jest-runner): handle test failures with circular objects
  CHANGELOG.md
  e2e/__tests__/__snapshots__/circularInequality.test.ts.snap
  e2e/__tests__/circularInequality.test.ts
  packages/jest-runner/src/index.ts
Labels: cla signed

#10990 chore: update emittery
  package.json
  packages/jest-core/package.json
  packages/jest-core/src/TestWatcher.ts
  packages/jest-runner/package.json
  packages/jest-runner/src/index.ts
  packages/jest-runner/src/types.ts
  yarn.lock
Labels: cla signed
