Repository jestjs/jest, pull requests merged in 2020-05, with the labels that each got.

#9931 fix: don't run beforeAll/afterAll in skipped block
  CHANGELOG.md
  e2e/__tests__/skipBeforeAfterAll.test.ts
  e2e/before-all-skipped/__tests__/beforeAllFiltered.test.js
  e2e/before-all-skipped/package.json
  packages/jest-jasmine2/src/treeProcessor.ts
Labels: cla signed

#9946 fix: remove warning when mutating `require.cache`
  CHANGELOG.md
  packages/jest-runtime/src/index.ts
Labels: cla signed

#9945 Remove es5 builds
  .circleci/config.yml
  .eslintignore
  .eslintrc.js
  .github/workflows/nodejs.yml
  .gitignore
  CHANGELOG.md
  e2e/browser-support/browserTest.js
  jest.config.js
  karma.conf.js
  package.json
  packages/expect/package.json
  packages/jest-mock/package.json
  packages/pretty-format/package.json
  scripts/browserBuild.js
  scripts/build.js
  tsconfig.json
Labels: cla signed

#9943 chore: remove support for `browser` field in config
  CHANGELOG.md
  TestUtils.ts
  docs/Configuration.md
  e2e/__tests__/__snapshots__/moduleNameMapper.test.ts.snap
  e2e/__tests__/__snapshots__/resolveNoFileExtensions.test.ts.snap
  e2e/__tests__/__snapshots__/showConfig.test.ts.snap
  e2e/__tests__/resolveBrowserField.test.ts
  packages/jest-cli/src/init/__tests__/__snapshots__/init.test.js.snap
  packages/jest-config/src/Defaults.ts
  packages/jest-config/src/Deprecated.ts
  packages/jest-config/src/Descriptions.ts
  packages/jest-config/src/ValidConfig.ts
  packages/jest-config/src/__tests__/normalize.test.js
  packages/jest-config/src/index.ts
  packages/jest-config/src/normalize.ts
  packages/jest-core/src/lib/__tests__/__snapshots__/log_debug_messages.test.ts.snap
  packages/jest-resolve/package.json
  packages/jest-resolve/src/defaultResolver.ts
  packages/jest-resolve/src/index.ts
  packages/jest-resolve/src/types.ts
  packages/jest-runtime/src/__tests__/resolve_browser.test.js
  packages/jest-runtime/src/index.ts
  packages/jest-transform/src/__tests__/__snapshots__/script_transformer.test.js.snap
  packages/jest-types/src/Config.ts
  yarn.lock
Labels: cla signed

#9854 fix: remove `require.requireActual` and `require.requireMock`
  CHANGELOG.md
  packages/jest-environment/src/index.ts
  packages/jest-haste-map/src/lib/__tests__/dependencyExtractor.test.js
  packages/jest-haste-map/src/lib/dependencyExtractor.ts
  packages/jest-runtime/src/index.ts
Labels: cla signed

#9823 chore: require minimum typescript@3.8
  .github/workflows/nodejs.yml
  CHANGELOG.md
  package.json
  packages/babel-jest/package.json
  packages/babel-plugin-jest-hoist/package.json
  packages/diff-sequences/package.json
  packages/expect/package.json
  packages/jest-changed-files/package.json
  packages/jest-circus/package.json
  packages/jest-cli/package.json
  packages/jest-config/package.json
  packages/jest-console/package.json
  packages/jest-console/src/CustomConsole.ts
  packages/jest-core/package.json
  packages/jest-diff/package.json
  packages/jest-docblock/package.json
  packages/jest-each/package.json
  packages/jest-environment-jsdom/package.json
  packages/jest-environment-node/package.json
  packages/jest-environment/package.json
  packages/jest-fake-timers/package.json
  packages/jest-get-type/package.json
  packages/jest-globals/package.json
  packages/jest-haste-map/package.json
  packages/jest-jasmine2/package.json
  packages/jest-leak-detector/package.json
  packages/jest-matcher-utils/package.json
  packages/jest-message-util/package.json
  packages/jest-mock/package.json
  packages/jest-phabricator/package.json
  packages/jest-regex-util/package.json
  packages/jest-repl/package.json
  packages/jest-reporters/package.json
  packages/jest-resolve-dependencies/package.json
  packages/jest-resolve/package.json
  packages/jest-runner/package.json
  packages/jest-runtime/package.json
  packages/jest-serializer/package.json
  packages/jest-snapshot/package.json
  packages/jest-source-map/package.json
  packages/jest-test-result/package.json
  packages/jest-test-sequencer/package.json
  packages/jest-transform/package.json
  packages/jest-transform/src/types.ts
  packages/jest-types/package.json
  packages/jest-types/src/Global.ts
  packages/jest-util/package.json
  packages/jest-validate/package.json
  packages/jest-watcher/package.json
  packages/jest-worker/package.json
  packages/jest/package.json
  packages/pretty-format/package.json
  packages/test-utils/package.json
  scripts/buildTs.js
  yarn.lock
Labels: cla signed

#9129 feat(jest-circus): Fail tests if a test takes a done callback and have return values
  CHANGELOG.md
  e2e/__tests__/__snapshots__/asyncAndCallback.test.ts.snap
  e2e/__tests__/asyncAndCallback.test.ts
  e2e/promise-and-callback/__tests__/promise-and-callback.test.js
  e2e/promise-and-callback/package.json
  packages/jest-circus/package.json
  packages/jest-circus/src/run.ts
  packages/jest-circus/src/utils.ts
Labels: cla signed

#9583 Remove `providesModuleNodeModules` from Jest.
  CHANGELOG.md
  TestUtils.ts
  e2e/__tests__/__snapshots__/showConfig.test.ts.snap
  packages/jest-config/src/Defaults.ts
  packages/jest-config/src/ValidConfig.ts
  packages/jest-core/src/__tests__/SearchSource.test.ts
  packages/jest-core/src/lib/__tests__/__snapshots__/log_debug_messages.test.ts.snap
  packages/jest-haste-map/src/__tests__/index.test.js
  packages/jest-haste-map/src/index.ts
  packages/jest-runtime/src/__tests__/runtime_require_module.test.js
  packages/jest-runtime/src/index.ts
  packages/jest-transform/src/__tests__/__snapshots__/script_transformer.test.js.snap
  packages/jest-types/src/Config.ts
  packages/jest-validate/src/__tests__/__snapshots__/validate.test.ts.snap
  packages/jest-validate/src/__tests__/fixtures/jestConfig.ts
  packages/jest-validate/src/__tests__/validate.test.ts
  website/versioned_docs/version-22.x/TutorialReactNative.md
  yarn.lock
Labels: cla signed

#9948 Remove leftover `providesModuleNodeModules`
  packages/jest-core/src/__tests__/SearchSource.test.ts
Labels: cla signed

#9949 chore: remove checks for compileFunction
  docs/CLI.md
  docs/Configuration.md
  e2e/__tests__/__snapshots__/globals.test.ts.snap
  e2e/__tests__/globals.test.ts
  packages/jest-runner/src/runTest.ts
  packages/jest-runtime/src/index.ts
Labels: cla signed

#9606 feat: upgrade to JSDOM 16
  CHANGELOG.md
  e2e/__tests__/__snapshots__/consoleLogOutputWhenRunInBand.test.ts.snap
  e2e/__tests__/consoleLogOutputWhenRunInBand.test.ts
  e2e/__tests__/jestEnvironmentJsdom.test.ts
  packages/jest-environment-jsdom/package.json
  packages/jest-environment-jsdom/src/index.ts
  yarn.lock
Labels: cla signed

#9938 chore: run some jsdom tests in leak check
  package.json
Labels: cla signed

#9765 Fix time duration formatting as per SI
  CHANGELOG.md
  CONTRIBUTING.md
  e2e/Utils.ts
  e2e/__tests__/overrideGlobals.test.ts
  packages/jest-circus/src/utils.ts
  packages/jest-console/src/BufferedConsole.ts
  packages/jest-console/src/CustomConsole.ts
  packages/jest-jasmine2/src/__tests__/queueRunner.test.ts
  packages/jest-jasmine2/src/queueRunner.ts
  packages/jest-reporters/src/__tests__/__snapshots__/summary_reporter.test.js.snap
  packages/jest-reporters/src/get_result_header.ts
  packages/jest-reporters/src/utils.ts
  packages/jest-reporters/src/verbose_reporter.ts
  packages/jest-util/src/__tests__/formatTime.test.ts
  packages/jest-util/src/formatTime.ts
  packages/jest-util/src/index.ts
  packages/pretty-format/package.json
  packages/pretty-format/perf/test.js
Labels: cla signed

#9951 chore: bump dated dependencies
  package.json
  packages/jest-changed-files/package.json
  packages/jest-circus/package.json
  packages/jest-message-util/package.json
  packages/jest-message-util/src/__tests__/__snapshots__/messages.test.ts.snap
  packages/jest-reporters/package.json
  packages/jest-runtime/package.json
  packages/jest-runtime/src/index.ts
  packages/jest-snapshot/package.json
  packages/jest-validate/package.json
  packages/jest-validate/src/validateCLIOptions.ts
  packages/jest-watcher/package.json
  packages/test-utils/package.json
  yarn.lock
Labels: cla signed

#9952 chore: remove dependency on `realpath-native`
  CHANGELOG.md
  e2e/__tests__/__snapshots__/moduleNameMapper.test.ts.snap
  e2e/__tests__/__snapshots__/resolveNoFileExtensions.test.ts.snap
  e2e/__tests__/hasteMapSize.test.ts
  package.json
  packages/jest-cli/package.json
  packages/jest-cli/src/cli/index.ts
  packages/jest-cli/src/init/index.ts
  packages/jest-config/package.json
  packages/jest-config/src/getCacheDirectory.ts
  packages/jest-config/src/index.ts
  packages/jest-config/src/normalize.ts
  packages/jest-core/package.json
  packages/jest-core/src/runJest.ts
  packages/jest-resolve/package.json
  packages/jest-resolve/src/__tests__/resolve.test.ts
  packages/jest-resolve/src/defaultResolver.ts
  packages/jest-resolve/src/index.ts
  packages/jest-resolve/src/nodeModulesPaths.ts
  packages/jest-runtime/package.json
  packages/jest-runtime/src/cli/index.ts
  packages/jest-transform/package.json
  packages/jest-transform/src/ScriptTransformer.ts
  packages/jest-transform/src/__tests__/script_transformer.test.js
  packages/jest-util/src/index.ts
  packages/jest-util/src/tryRealpath.ts
Labels: cla signed

#8662 Update jest-phabricator documentation
  CHANGELOG.md
  packages/jest-phabricator/README.md
Labels: cla signed

#8583 Updated config docs - transform
  CHANGELOG.md
  docs/Configuration.md
  website/versioned_docs/version-22.x/Configuration.md
  website/versioned_docs/version-23.x/Configuration.md
  website/versioned_docs/version-24.x/Configuration.md
  website/versioned_docs/version-25.1/Configuration.md
  website/versioned_docs/version-25.3/Configuration.md
  website/versioned_docs/version-25.5/Configuration.md
Labels: Documentation :book:, cla signed

#9953 chore: update ts-eslint
  package.json
  packages/expect/src/extractExpectedAssertionsErrors.ts
  packages/jest-circus/src/formatNodeAssertErrors.ts
  packages/jest-core/src/lib/active_filters_message.ts
  packages/jest-core/src/plugins/quit.ts
  packages/jest-core/src/plugins/test_name_pattern.ts
  packages/jest-core/src/plugins/test_path_pattern.ts
  packages/jest-core/src/plugins/update_snapshots.ts
  packages/jest-core/src/plugins/update_snapshots_interactive.ts
  packages/jest-diff/src/index.ts
  packages/jest-each/src/index.ts
  packages/jest-environment-jsdom/src/index.ts
  packages/jest-haste-map/src/getMockName.ts
  packages/jest-haste-map/src/lib/normalizePathSep.ts
  packages/jest-jasmine2/src/assertionErrorMessage.ts
  packages/jest-types/src/Circus.ts
  packages/jest-validate/src/validate.ts
  packages/jest-watcher/src/BaseWatchPlugin.ts
  packages/jest-watcher/src/JestHooks.ts
  yarn.lock
Labels: cla signed

#8096 jest-circus: throw if a test / hook is defined asynchronously
  CHANGELOG.md
  e2e/__tests__/__snapshots__/circusDeclarationErrors.test.ts.snap
  e2e/__tests__/beforeEachQueue.ts
  e2e/__tests__/circusDeclarationErrors.test.ts
  e2e/circus-declaration-errors/__tests__/asyncDefinition.test.js
  e2e/circus-declaration-errors/package.json
  packages/jest-circus/src/eventHandler.ts
  packages/jest-circus/src/state.ts
  packages/jest-types/src/Circus.ts
Labels: cla signed

#9955 fix: handle `null` being passed to `createTransformer`
  CHANGELOG.md
  e2e/__tests__/__snapshots__/transform.test.ts.snap
  packages/babel-jest/src/__tests__/index.ts
  packages/babel-jest/src/index.ts
Labels: cla signed

#9174 updated docs regarding testSequencer
  docs/Configuration.md
  website/versioned_docs/version-24.x/Configuration.md
  website/versioned_docs/version-25.5/Configuration.md
Labels: Documentation :book:, cla signed

#9106 docs: Updated Testing Frameworks guide with React; make it generic
  CHANGELOG.md
  docs/TestingFrameworks.md
  website/versioned_docs/version-25.1/TestingFrameworks.md
Labels: Documentation :book:, cla signed

#9095 Update index.js
  website/pages/en/index.js
Labels: cla signed

#9960 chore: rename LolexFakeTimers to ModernFakeTimers
  CHANGELOG.md
  packages/jest-environment-jsdom/src/__tests__/jsdom_environment.test.ts
  packages/jest-environment-jsdom/src/index.ts
  packages/jest-environment-node/src/__tests__/node_environment.test.ts
  packages/jest-environment-node/src/index.ts
  packages/jest-environment/src/index.ts
  packages/jest-fake-timers/package.json
  packages/jest-fake-timers/src/__tests__/__snapshots__/legacyFakeTimers.test.ts.snap
  packages/jest-fake-timers/src/__tests__/__snapshots__/modernFakeTimers.test.ts.snap
  packages/jest-fake-timers/src/__tests__/legacyFakeTimers.test.ts
  packages/jest-fake-timers/src/__tests__/modernFakeTimers.test.ts
  packages/jest-fake-timers/src/index.ts
  packages/jest-fake-timers/src/legacyFakeTimers.ts
  packages/jest-fake-timers/src/modernFakeTimers.ts
  yarn.lock
Labels: cla signed

#7776 feat: add new 'modern' implementation of Fake Timers
  CHANGELOG.md
  docs/Configuration.md
  docs/JestObjectAPI.md
  e2e/__tests__/modernFakeTimers.test.ts
  e2e/modern-fake-timers/from-config/__tests__/test.js
  e2e/modern-fake-timers/from-config/package.json
  e2e/modern-fake-timers/from-jest-object/__tests__/test.js
  e2e/modern-fake-timers/from-jest-object/package.json
  packages/jest-circus/src/legacy-code-todo-rewrite/jestAdapter.ts
  packages/jest-environment/src/index.ts
  packages/jest-jasmine2/src/index.ts
  packages/jest-runtime/package.json
  packages/jest-runtime/src/index.ts
  packages/jest-runtime/tsconfig.json
  packages/jest-types/src/Config.ts
Labels: cla signed

#9963 chore: improve error on module not found
  CHANGELOG.md
  e2e/__tests__/stackTrace.test.ts
  e2e/resolve/__tests__/resolve.test.js
  packages/jest-resolve/src/index.ts
Labels: cla signed

#9962 feat: add `createMockFromModule` to replace `genMockFromModule`
  CHANGELOG.md
  docs/JestObjectAPI.md
  docs/ManualMocks.md
  e2e/runtime-internal-module-registry/__mocks__/fs.js
  examples/automatic-mocks/__tests__/createMockFromModule.test.js
  examples/manual-mocks/__mocks__/fs.js
  examples/manual-mocks/__mocks__/lodash.js
  examples/manual-mocks/models/__mocks__/user.js
  examples/module-mock/__tests__/partial_mock.js
  packages/jest-config/src/__mocks__/fs.js
  packages/jest-config/src/__mocks__/os.js
  packages/jest-environment-jsdom/src/__mocks__/index.ts
  packages/jest-environment/src/index.ts
  packages/jest-haste-map/src/__tests__/worker.test.js
  packages/jest-haste-map/src/lib/__tests__/dependencyExtractor.test.js
  packages/jest-haste-map/src/lib/dependencyExtractor.ts
  packages/jest-regex-util/src/__tests__/index.test.ts
  packages/jest-reporters/src/__tests__/coverage_reporter.test.js
  packages/jest-runtime/src/__tests__/runtime_create_mock_from_module.test.js
  packages/jest-runtime/src/__tests__/test_root/mapped_module_createMockFromModule.js
  packages/jest-runtime/src/index.ts
  packages/jest-snapshot/src/__tests__/inline_snapshots.test.ts
  packages/jest-snapshot/src/__tests__/utils.test.ts
  packages/jest-source-map/src/__tests__/getCallsite.test.ts
  packages/jest-test-sequencer/src/__tests__/test_sequencer.test.js
  packages/jest-transform/src/__tests__/script_transformer.test.js
Labels: cla signed

#9964 chore: fix windows CI
  e2e/__tests__/__snapshots__/moduleNameMapper.test.ts.snap
  e2e/__tests__/__snapshots__/resolveNoFileExtensions.test.ts.snap
  packages/jest-resolve/src/index.ts
Labels: cla signed

#7347 Fix invalid re-run of tests in watch mode
  CHANGELOG.md
  e2e/__tests__/watchModeNoAccess.test.ts
  packages/jest-haste-map/src/index.ts
Labels: cla signed

#9965 align circus with jasmine's top-to-bottom execution order
  CHANGELOG.md
  e2e/__tests__/__snapshots__/globals.test.ts.snap
  e2e/__tests__/globals.test.ts
  packages/jest-circus/src/eventHandler.ts
  packages/jest-circus/src/run.ts
  packages/jest-circus/src/utils.ts
  packages/jest-types/src/Circus.ts
Labels: cla signed, 💣 Breaking change

#9966 chore: skip broken test on windows
  e2e/__tests__/watchModeNoAccess.test.ts
Labels: cla signed

#9967 chore: fix watch mode test with utimes
  e2e/__tests__/watchModeNoAccess.test.ts
Labels: cla signed

#8727 fix: absolute path moduleNameMapper + jest.mock issue
  CHANGELOG.md
  e2e/__tests__/__snapshots__/moduleNameMapper.test.ts.snap
  e2e/__tests__/moduleNameMapper.test.ts
  e2e/module-name-mapper-correct-mock-absolute-path/__tests__/index.js
  e2e/module-name-mapper-correct-mock-absolute-path/index.js
  e2e/module-name-mapper-correct-mock-absolute-path/package.json
  e2e/module-name-mapper-correct-mock-absolute-path/src/components/Button.js
  packages/jest-runtime/src/index.ts
Labels: cla signed

#9957 fix: disallow hook definitions in tests
  CHANGELOG.md
  e2e/__tests__/__snapshots__/circusDeclarationErrors.test.ts.snap
  e2e/__tests__/nestedTestDefinitions.test.ts
  e2e/nested-test-definitions/__tests__/nestedHookInTest.js
  packages/jest-circus/src/eventHandler.ts
  packages/jest-circus/src/formatNodeAssertErrors.ts
  packages/jest-types/src/Circus.ts
Labels: cla signed

#9956 docs: create v26, fold v25.x into a single version
  website/versioned_docs/version-25.1/TutorialReact.md
  website/versioned_docs/version-25.3/JestObjectAPI.md
  website/versioned_docs/version-25.5/Configuration.md
  website/versioned_docs/version-25.x/CLI.md
  website/versioned_docs/version-25.x/Configuration.md
  website/versioned_docs/version-25.x/Es6ClassMocks.md
  website/versioned_docs/version-25.x/ExpectAPI.md
  website/versioned_docs/version-25.x/GlobalAPI.md
  website/versioned_docs/version-25.x/JestObjectAPI.md
  website/versioned_docs/version-25.x/JestPlatform.md
  website/versioned_docs/version-25.x/MockFunctions.md
  website/versioned_docs/version-25.x/TestingAsyncCode.md
  website/versioned_docs/version-25.x/TestingFrameworks.md
  website/versioned_docs/version-25.x/Troubleshooting.md
  website/versioned_docs/version-25.x/TutorialAsync.md
  website/versioned_docs/version-25.x/TutorialReact.md
  website/versioned_docs/version-25.x/TutorialReactNative.md
  website/versioned_docs/version-26.0/CLI.md
  website/versioned_docs/version-26.0/Configuration.md
  website/versioned_docs/version-26.0/JestPlatform.md
  website/versions.json
Labels: Documentation :book:, cla signed

#9975 chore: update to weak-napi@2
  packages/jest-leak-detector/package.json
  yarn.lock
Labels: cla signed

#9950 Add Jest 26 blog post
  website/blog/2020-05-06-jest-26.md
Labels: cla signed

#9977 chore: fix date and heading in blog post
  website/blog/2020-05-05-jest-26.md
Labels: cla signed

#9978 Add migration notes for breaking changes
  website/blog/2020-05-05-jest-26.md
Labels: cla signed

#9985 docs: fix Configuration, JestPlatform and JestObjectAPI docs for 26
  website/versioned_docs/version-26.0/Configuration.md
  website/versioned_docs/version-26.0/JestObjectAPI.md
  website/versioned_docs/version-26.0/JestPlatform.md
Labels: cla signed

#9994 docs: fix jest-object ids for docusaurs
  website/versioned_docs/version-26.0/JestObjectAPI.md
Labels: cla signed

#9990 fix(jest-jasmine2): fix Error message
  CHANGELOG.md
  packages/jest-jasmine2/src/__tests__/expectationResultFactory.test.ts
  packages/jest-jasmine2/src/expectationResultFactory.ts
Labels: cla signed

#9997 fix: Control no diff message color with diff options
  CHANGELOG.md
  packages/jest-diff/src/__tests__/__snapshots__/diff.test.ts.snap
  packages/jest-diff/src/__tests__/diff.test.ts
  packages/jest-diff/src/constants.ts
  packages/jest-diff/src/index.ts
Labels: cla signed

#9999 chore: add missing comma
  website/pages/en/index.js
Labels: cla signed

#10006 Fix dependency warning typo for `browser` config field
  packages/jest-config/src/Deprecated.ts
Labels: cla signed

#10000 🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉
  CHANGELOG.md
  packages/jest-core/src/cli/index.ts
Labels: cla signed

#10008 fix: add missing haste-map dep to jest-snapshot
  CHANGELOG.md
  packages/jest-snapshot/package.json
Labels: cla signed

#10001 feat: support config files exporting (`async`) `function`s
  CHANGELOG.md
  docs/Configuration.md
  packages/jest-config/src/__tests__/readConfigs.test.ts
  packages/jest-config/src/index.ts
Labels: cla signed

#10009 chore: bump `istanbul-lib-instrument`
  packages/jest-reporters/package.json
  packages/jest-transform/src/__tests__/__snapshots__/script_transformer.test.js.snap
  packages/jest-transform/src/__tests__/script_transformer.test.js
  yarn.lock
Labels: cla signed

#8612 feat: CLI argument to filter tests by projects
  CHANGELOG.md
  docs/CLI.md
  e2e/__tests__/selectProjects.test.ts
  e2e/runJest.ts
  e2e/select-projects-missing-name/__tests__/first-project.test.js
  e2e/select-projects-missing-name/__tests__/second-project.test.js
  e2e/select-projects-missing-name/package.json
  e2e/select-projects/__tests__/first-project.test.js
  e2e/select-projects/__tests__/second-project.test.js
  e2e/select-projects/package.json
  packages/jest-cli/src/__tests__/cli/args.test.ts
  packages/jest-cli/src/cli/args.ts
  packages/jest-core/src/cli/index.ts
  packages/jest-core/src/getConfigsOfProjectsToRun.ts
  packages/jest-core/src/getProjectDisplayName.ts
  packages/jest-core/src/getProjectNamesMissingWarning.ts
  packages/jest-core/src/getSelectProjectsMessage.ts
  packages/jest-types/src/Config.ts
Labels: cla signed

#10033 Minor test name typo fix
  e2e/__tests__/filter.test.ts
Labels: cla signed

#10034 chore: fix TestUtils.ts to match the types
  TestUtils.ts
  packages/jest-core/src/lib/__tests__/__snapshots__/log_debug_messages.test.ts.snap
  packages/jest-transform/src/__tests__/__snapshots__/script_transformer.test.js.snap
Labels: cla signed

#10050 chore: minor optimize getTransformer
  packages/jest-transform/src/ScriptTransformer.ts
Labels: cla signed

#10055 docs: correct confusing filename in `enableAutomock` example
  CHANGELOG.md
  docs/JestObjectAPI.md
  website/versioned_docs/version-26.0/JestObjectAPI.md
Labels: cla signed

#10049 Cleanup `displayName` type
  CHANGELOG.md
  packages/jest-core/src/getProjectDisplayName.ts
  packages/jest-reporters/src/__tests__/utils.test.ts
  packages/jest-reporters/src/utils.ts
  packages/jest-test-result/src/helpers.ts
  packages/jest-types/src/Config.ts
Labels: cla signed

#10067 docs: fix jest-diff example
  docs/JestPlatform.md
Labels: cla signed

#9907 Jest-internal sandbox escape hatch
  CHANGELOG.md
  packages/jest-runtime/src/__tests__/runtime_require_resolve.test.ts
  packages/jest-runtime/src/__tests__/test_root/resolve_and_require_outside.js
  packages/jest-runtime/src/__tests__/test_root/resolve_mapped.js
  packages/jest-runtime/src/__tests__/test_root/resolve_self.js
  packages/jest-runtime/src/helpers.ts
  packages/jest-runtime/src/index.ts
Labels: cla signed

#10107 chore: Remove references to ftest alias
  docs/GlobalAPI.md
  website/versioned_docs/version-25.x/GlobalAPI.md
Labels: cla signed

#10109 Add `coverageProvider` to `jest --init` prompt
  CHANGELOG.md
  packages/jest-cli/src/init/__tests__/__snapshots__/init.test.js.snap
  packages/jest-cli/src/init/__tests__/init.test.js
  packages/jest-cli/src/init/generate_config_file.ts
  packages/jest-cli/src/init/index.ts
  packages/jest-cli/src/init/questions.ts
  packages/jest-config/src/Descriptions.ts
Labels: cla signed
