Repository jestjs/jest, pull requests merged in 2023-09, with the labels that each got.

#13825 feat: upgrade to JSDOM@22
  CHANGELOG.md
  packages/jest-environment-jsdom/package.json
  yarn.lock
Labels: cla signed, Pinned

#13417 Improve `detectOpenHandles`
  CHANGELOG.md
  e2e/__tests__/__snapshots__/detectOpenHandles.ts.snap
  packages/jest-core/src/__tests__/collectHandles.test.js
  packages/jest-core/src/collectHandles.ts
Labels: cla signed

#14072 chore: update typebox dependencies
  CHANGELOG.md
  packages/jest-schemas/package.json
  yarn.lock
Labels: cla signed, Pinned

#12348 feat: bundle Jest's modules with webpack
  CHANGELOG.md
  e2e/__tests__/__snapshots__/circusDeclarationErrors.test.ts.snap
  e2e/__tests__/__snapshots__/moduleNameMapper.test.ts.snap
  e2e/__tests__/__snapshots__/requireMissingExt.test.ts.snap
  e2e/__tests__/__snapshots__/resolveNoFileExtensions.test.ts.snap
  e2e/__tests__/__snapshots__/showConfig.test.ts.snap
  e2e/__tests__/__snapshots__/testFailingJasmine.test.ts.snap
  e2e/__tests__/__snapshots__/transform.test.ts.snap
  e2e/__tests__/stackTrace.test.ts
  package.json
  packages/jest-circus/package.json
  packages/jest-circus/src/runner.ts
  packages/jest-config/src/normalize.ts
  packages/jest-config/src/readConfigFileAndSetRootDir.ts
  packages/jest-runner/src/runTest.ts
  packages/jest-util/src/requireOrImportModule.ts
  scripts/build.mjs
  scripts/buildUtils.mjs
  scripts/bundleTs.mjs
  yarn.lock
Labels: cla signed, Pinned

#14109 Babel option rename (blacklist -> denylist)
  CHANGELOG.md
  packages/babel-jest/package.json
  packages/babel-plugin-jest-hoist/src/index.ts
  packages/babel-preset-jest/package.json
  yarn.lock
Labels: Pinned

#13965 feat(jest-snapshot): Support Error.cause in snapshots
  CHANGELOG.md
  e2e/__tests__/__snapshots__/toThrowErrorMatchingInlineSnapshot.test.ts.snap
  e2e/__tests__/toThrowErrorMatchingInlineSnapshot.test.ts
  packages/jest-snapshot/src/index.ts
Labels: cla signed, Pinned

#14175 docs(SnapshotTesting.md): Additionally mention snapshot serializer in "replacing random string part" section
  docs/SnapshotTesting.md
  website/versioned_docs/version-29.4/SnapshotTesting.md
  website/versioned_docs/version-29.5/SnapshotTesting.md
  website/versioned_docs/version-29.6/SnapshotTesting.md
  website/versioned_docs/version-29.7/SnapshotTesting.md
Labels: Stale
